### ISSUE TITLE
As a fan or manager, I want everything I can see on the web page to be in a menu tab.

### ISSUE THREAD

**Issue by MekanMyradov** [SU-CS308-22FA/Team27_Oneplayer#1]
**Definition of Done**
The fact that all the information to be accessed and the activities that can be done on the web page are in a menu makes the web page look more organized, easier and more effective to use.

**Comment by selinbsa** [comment]
**Definition of Done**
The fact that all the information to be accessed and the activities that can be done on the web page are in a menu makes the web page look more organized, easier and more effective to use.
